### ISSUE TITLE
Whether Siemens opc server operation is supported

### ISSUE THREAD

**Issue by HOULL2** [konimarti/opc#13]
Whether Siemens opc server operation is supported, such as OPC. SimaticNET. 1. 
Whether to support the Kepware. KEPServerEX. V6 server

**Comment by konimarti** [comment]
Any standard OPC DA server should work. The package provides sync read/write and browsing operations.  #11 confirms that it works with KepServerEx V6. Note, however, that you need an OPC automation wrapper (which is usually ships with your OPC server and is installed with it) and also proper COM/DCOM settings.
