### ISSUE TITLE
Username&&Password

### ISSUE THREAD

**Issue by AlexWuDDD** [konimarti/opc#24]
how to use username and password to connect the opc sever?

**Comment by konimarti** [comment]
@AlexWuDDD OPC DA uses DCOM to connect to OPC DA servers. The username and password is for your windows account and you can set permissions with dcomcnfg.exe for different users. Your questions is related to the setup of an OPC DA server and has nothing to do with this package.

**Comment by AlexWuDDD** [comment]
very appreciate
