### ISSUE TITLE
strange issue

### ISSUE THREAD

**Issue by AlexWuDDD** [konimarti/opc#25]
First, i can read the date from the remote Matrikon Simulation Server  using your package
Second, i try to connect another OPC sever, but what is strange is that Matrikon Explore can connect the remote server, but the application with your package cannot, error is "TryConnect was not successful: Connection failed". 
And explore and the application on the same machine. OPC Sever is in the another PC.
Could you please suggest something for me?

**Comment by AlexWuDDD** [comment]
And show the server  list can work

**Comment by konimarti** [comment]
The server list uses the OPCenum.exe when I remember it correctly. The difference between matrikon explorer and this package is that the explorer uses the opc custom interface and this package uses the opc automation wrapper. For further information, i'd suggest that you google for "opc da automation wrapper".
