### ISSUE TITLE
Is that possible to browse all tags on a running OPC server using this library ?

### ISSUE THREAD

**Issue by giter** [konimarti/opc#3]

**Comment by konimarti** [comment]
This is not implemented yet but can be done. Highly appreciated if you
would like to contribute and implement it.

**Comment by giter** [comment]
I'd like to , but I really know nothing about OLE technology,  any advice?

**Comment by konimarti** [comment]
Please check out #4 and see if that is what you need. 

I'm not an OLE expert either but what helps a lot is the MS Visual Basic editor where you can use the "Object Explorer" for the "OPC Automation Wrapper" DLL. Plus the OPC Automation Wrapper documentation is excellent.
