### ISSUE TITLE
Connection not closed after function "CreateBrowser" execution

### ISSUE THREAD

**Issue by Hejianxiong** [konimarti/opc#33]
//CreateBrowser creates an opc browser representation
func CreateBrowser(server string, nodes []string) (*Tree, error) {
	object := NewAutomationObject()
	defer object.Close()
	_, err := object.TryConnect(server, nodes)
	if err != nil {
		return nil, err
	}
	return object.CreateBrowser()
}

object.TryConnect(server, nodes)  will create one connection ,however connection does`'t close after  execution

**Comment by konimarti** [comment]
#31
