### ISSUE TITLE
reconnect &  read opc data is zero

### ISSUE THREAD

**Issue by ymmemo** [konimarti/opc#36]
I test the connect lost & reconnect, than read opc data is zero.
there may be a bug here

```
func (conn *opcConnectionImpl) fix() {
	var err error
	if !conn.IsConnected() {
		for {
			tags := conn.Tags() // tags empty
```
 If I have misinterpreted the expected behavior here, and there is a better way to do this please let me know.
thank you.

**Comment by konimarti** [comment]
Please check the quality return value of the opc item to check wheather the data read was successfull or not. When it is zero, it is not ok according to the opc da specification.
