### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SSSOCPaulCote** [konimarti/opc#38]
I cloned the repo, and ran `go test -v ./...` but I keep getting this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1015168]
```
Manually testing this package by trying to follow the example on the main page with a running OPC server on my PC also yields this result.

I'm running go 1.17.1 on Windows 10. Here's my test code:
```
package main

import (
	"fmt"
	"github.com/konimarti/opc"
)

func main() {
	c, _ := opc.NewConnection(
		"Fluke.DAQ.OPC",
		[]string{"DESKTOP-<redacted>"},
		[]string{"Instrument 01.Module 3.Channel 304"},
	)
	defer c.Close()
	fmt.Println(c.Read())
}
```

**Comment by SSSOCPaulCote** [comment]
Investigating and it might have to do with `NewAutomationObject` method in `connection_windows.go`. At line 223, you declare a pointer of type `ole.IUnknown` as such `var unknown *ole.IUknown` but maybe anytime you declare a pointer, you should do it this way `var unknown *ole.IUnknown = new(ole.IUnknown)` based on [this article](https://yourbasic.org/golang/gotcha-nil-pointer-dereference/)

**Comment by konimarti** [comment]
Did you go through the Troubleshooting section? Try setting the architecture to $ENV:GOARCH="386" in Powershell and compile everything again. Most of the time, this is the issue or a wrong ProgID. Also, please add opc.Debug() before the opc.NewConnection call to print more debug-related information.

**Comment by SSSOCPaulCote** [comment]
@konimarti setting `GOARCH` to 386 worked. Thank you for responding. I'll close this issue!
