### ISSUE TITLE
How to confirm param in opc.NewConnection

### ISSUE THREAD

**Issue by boundray** [konimarti/opc#46]
use matrikon simulator
the matrikon explore window like this:
![image](https://user-images.githubusercontent.com/15626624/196429298-bcc38465-4940-4815-91d9-8c54d510aacd.png)
question: how to fill in the opc.NewConnection parameters?

**Comment by boundray** [comment]
my code and err as shown here:
![image](https://user-images.githubusercontent.com/15626624/196683923-a5c571f3-9f33-48fc-a5f8-a491b2f0561d.png)

**Comment by konimarti** [comment]
Can you retry with the latest master? I just pushed a fix that should include the Matrikon automation object. Also, please double check that you compile the code for the 386 architecture as discussed in the README.

**Comment by boundray** [comment]
Successfully run after code merging and environment 386 set.
thanks.

**Comment by doffi88** [comment]
@boundray  how do you manage to talk to the matrikon server?
