### ISSUE TITLE
DCOM hardening in gray box module

### ISSUE THREAD

**Issue by duduyoyo** [konimarti/opc#57]
I checked the dependent dll used in this project (auto DA wrapper from gray box) and found out that dll was compiled in 2008/2011 respectively for 32/64 bit OS. This would be an issue for servers which have applied MS DCOM hardening in recent years. Has anyone encountered any connection issue?

Another alternative is [this](https://github.com/duduyoyo/WebSocket4OPC). Since Go supports WebSocket, so we can take advantage of this to retrieve DA data back without this auto DA wrapper. Has anyone tried? There is no client sample code on Go from that repository unfortunately.

**Comment by konimarti** [comment]
You must have misunderstand a few things. The Graybox DLL is just used for local testing of the code. In real situations the opc components dll from your current OPC server will be used. For reference, this package also ships the opcapi binary which exposes a JSON-based REST API server-side to access OPC data from different machines without relying on DCOM. Anyways, your post seems more about promoting your own code which is fine with me. Thanks for sharing.
